### ISSUE TITLE
Start executing at next measure

### ISSUE THREAD

**Issue by doesntgolf** [charlieroberts/gibber.lib#10]
Hey Charlie,

Is there a way in gibber.lib to emulate Gibber's Shift+Enter to start executing code at the start of the following measure?

Thanks!

**Comment by charlieroberts** [comment]
Hi Nate,

Sure. The `Gibber.Audio.Clock` singleton object is what schedules these events. It has a `codeToExecute` property that allows you to schedule either functions to be executed (probably preferred) or strings of raw code to be eval'd. So, for example, the following should work:

```javascript
var test = {
  function: function() { console.log( 'TESTING') }
}

Gibber.Audio.Clock.codeToExecute.push( test )
```

If you want to pass strings for evaluation, just use the key `code` instead of `function` int he above object. Hope this helps! - Charlie

**Comment by doesntgolf** [comment]
Awesome, couldn't be simpler. Thanks much for the quick help!
